# Generated by Django 3.1.3 on 2020-12-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bewertung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=10, unique=True)),
                ('beschreibung', models.CharField(max_length=50)),
                ('wert', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Bewertung',
            },
        ),
        migrations.AlterModelOptions(
            name='tagebuch',
            options={'verbose_name_plural': 'Tagebuch'},
        ),
    ]
