# Generated by Django 3.1.3 on 2020-12-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20201202_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bewertung',
            name='slug',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
