# Generated by Django 3.1.3 on 2020-12-02 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20201202_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagebuch',
            name='bewertung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.bewertung'),
        ),
    ]
